# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'shard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bshard.proto\x12\x05shard\"\x86\x01\n\rInsertRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x34\n\x08metadata\x18\x02 \x03(\x0b\x32\".shard.InsertRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x0eInsertResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"0\n\rSearchRequest\x12\x14\n\x0cquery_vector\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"\x8f\x01\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x33\n\x08metadata\x18\x03 \x03(\x0b\x32!.shard.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x0eSearchResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.shard.SearchResult\"\x14\n\x12HealthCheckRequest\":\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nitem_count\x18\x02 \x01(\x05\x32\xc2\x01\n\x0cShardService\x12\x35\n\x06Insert\x12\x14.shard.InsertRequest\x1a\x15.shard.InsertResponse\x12\x35\n\x06Search\x12\x14.shard.SearchRequest\x1a\x15.shard.SearchResponse\x12\x44\n\x0bHealthCheck\x12\x19.shard.HealthCheckRequest\x1a\x1a.shard.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INSERTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHRESULT_METADATAENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INSERTREQUEST']._serialized_start=23
  _globals['_INSERTREQUEST']._serialized_end=157
  _globals['_INSERTREQUEST_METADATAENTRY']._serialized_start=110
  _globals['_INSERTREQUEST_METADATAENTRY']._serialized_end=157
  _globals['_INSERTRESPONSE']._serialized_start=159
  _globals['_INSERTRESPONSE']._serialized_end=192
  _globals['_SEARCHREQUEST']._serialized_start=194
  _globals['_SEARCHREQUEST']._serialized_end=242
  _globals['_SEARCHRESULT']._serialized_start=245
  _globals['_SEARCHRESULT']._serialized_end=388
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=110
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=157
  _globals['_SEARCHRESPONSE']._serialized_start=390
  _globals['_SEARCHRESPONSE']._serialized_end=444
  _globals['_HEALTHCHECKREQUEST']._serialized_start=446
  _globals['_HEALTHCHECKREQUEST']._serialized_end=466
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=468
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=526
  _globals['_SHARDSERVICE']._serialized_start=529
  _globals['_SHARDSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
